<?=
$this->action("header", "index", "Sub", array(
    'language' => $this->language,
    'moduleTitle' => $this->module,
    'meta_desc'=>$this->meta['desc'],
    'meta_key'=>$this->meta['key']
))
?>
<?php
$colors = array(
    //"color-orange",
    "color-blue");
$color = $colors[rand(0, count($colors) - 1)];
?>
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="color-white">
                <div class="post">
                     <div class="clearfix">
                        <div class="pull-left">
                            <h1 class="post-title">
                               <?= $this->post['title'] ?>
                            </h1>
                        </div>
                        <div class="pull-right post-date">
                            <span class="fa fa-clock-o"></span> <?= date("H:i:s | d/m/Y")?>
                        </div>
                    </div>

                    <div id="view-img-map" class="post-content clearfix">
                        <?php if($this->post['img']):?>
                        <div class="pull-left" style="max-width: 100%"><img src="<?=BASE_URL?>/files/images/about/<?=$this->post['img']?>" style="margin:0px;padding:5px 10px 0px 0px;max-width:100%"></div>
                        <?php endif;?>
                        <?= $this->post['content'] ?>
                    </div>
                    <?=
                    $this->action("share", "index", "Sub", array(
                        'language' => $this->language,
                        'moduleTitle' => $this->module))
                    ?>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <?=
            $this->action("submenu", "index", "Sub", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
            <?=
            $this->action("quickmenu", "index", "Sub", array(
                'language' => $this->language,
                'moduleTitle' => $this->module))
            ?>
            <?=
            $this->action("news", "index", "Sub", array(
                'language' => $this->language,
                'moduleTitle' => $this->module))
            ?>
        </div>
    </div>
</div>
<?=
$this->action("footer", "index", "Sub", array(
    'language' => $this->language,
    'moduleTitle' => $this->module))
?>