<?php
$date = $_REQUEST['date'] ? $_REQUEST['date'] : date('Y-m-d');
$cur = $_REQUEST['cur'] ? $_REQUEST['cur'] : 'AAVEUSDT';
$strDate = strtotime($date) . '000';


$symboyAlls=$this->symboyAlls;
$curDatas = [];
$curNext="";
if ($symboyAlls) {
    $flag = 0;
    foreach($symboyAlls as $row){
        $curDatas[] = $row['symbol'];
    }
    
    foreach($curDatas as $a){
        if ($flag) {
            $curNext = $a;
            break;
        }
        
        
        if ($a == $cur) {
            $flag = 1;
        }
    }
}

$url="http://dohome.vn/demo/vn/";
//$url='localhost'.BASE_URL;
if(!$flag || !$curNext) 
    die("OK");

?>

<html>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        var burl = "https://api.binance.com";

        var query = '/api/v3/klines';


        query += '?symbol=<?php echo($cur) ?>&interval=1d&startTime=<?php echo($strDate) ?>';

        var url = burl + query;

        var ourRequest = new XMLHttpRequest();
        var datas = [];
        ourRequest.open('GET', url, true);
        ourRequest.onload = function () {
            console.log(JSON.parse(ourRequest.responseText));
            var data = ourRequest.responseText;
            $.ajax({
                type: "POST",
                url: "http://dohome.vn/demo/vn/process",
                cache: false,
                data: {
                    'data': JSON.parse(data),
                    'symbol': '<?php echo($cur) ?>'
                },
                dataType: "json",
                success: function (response) {

                    if (!response.error) {
                        $("#msg").addClass('alert-success').html(response.msg);
                    } else {
                        $("#msg").addClass('alert-danger').html(response.msg);
                    }
                }
            });
        };
        ourRequest.send();

        var urlNext = 'http://dohome.vn/demo/vn/send?date=' + '<?php echo($date) ?>' + '&cur=' + '<?php echo($curNext) ?>';
        setTimeout(function(){
            window.location.href = urlNext;
        },100);


    </script>
    <body>
        <div id="msg"></div>
    </body>

</html>