<?php
$prices = $this->prices;
$formulars = $this->formulars;
$posts = $this->posts;
$postBtcs = $this->postBtcs;
$postCurrent = $this->postCurrent;
$histories = $this->histories;
$symbol = $this->symbol;

$activeUSD = 'active';
$activeBTC = 'active';

if (preg_match('/USDT/', $symbol)) {
    $activeBTC = "";
} else {
    $activeUSD = "";
}
?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Market Trading</title>

        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/style.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/icons.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/ui.css">

    </head>

    <body>
        <?php include 'p_header.phtml'; ?>
        <!-- Main Content -->

        <div class="container-fluid">
            <div class="row sm-gutters">

                <div class="col-md-12 col-lg-12 col-xl-12 col-xxl-9" >

                    <!-- TradingView Widget BEGIN -->
                    <div class="tradingview-widget-container mb-3">
                        <div id="crypt-candle-chart"></div>
                        <div id="view-detail">
                            <?php
                            if ($postCurrent) :
                                $dCurrent = $postCurrent['date_h4'];

                                $detail = [];
                                if ($postCurrent) {
                                    $detail = json_decode($postCurrent['json_details']);
                                    $formular = $formulars[$postCurrent['type_id']];
                                }
                                
                                ?>
                                <div class='container-right-title'>Chi tiết giá đồng <?php echo($symbol); ?> ngày <?php echo(date("d/m/Y", strtotime("+1 day" . $dCurrent))) ?></div>
                                <div class='view-detail-1'>
                                    <table class="table table-striped">
                                        <tbody class="crypt-table-hover">
                                            <tr>
                                                <td class="align-middle">
                                                    <b>Type:</b>
                                                </td>
                                                <td class="crypt-down align-middle">
                                                    <span style='color:green;font-weight: bold'> <?php echo($postCurrent['model_name']) ?></span>
                                                </td>

                                            </tr>
                                            <tr>
                                                <td class="align-middle">
                                                    <b>Entry Zone:</b>
                                                </td>
                                                <td class="crypt-down align-middle">
                                                    <span style='color:green;font-weight: bold'> <?php echo($detail->buylong) ?></span>
                                                </td>

                                            </tr>
                                            <tr>
                                                <td class="align-middle">
                                                    <b>Target_1:</b>
                                                </td>
                                                <td class="crypt-down align-middle">
                                                    <span style='color:green;font-weight: bold'> <?php echo($detail->target1) ?></span>
                                                </td>

                                            </tr>
                                            <tr>
                                                <td class="align-middle">
                                                    <b>Target_2:</b>
                                                </td>
                                                <td class="crypt-down align-middle">
                                                    <span style='color:green;font-weight: bold'> <?php echo($detail->target2) ?></span>
                                                </td>

                                            </tr>
                                            <tr>
                                                <td class="align-middle">
                                                    <b>Stoploss:</b>
                                                </td>
                                                <td class="crypt-down align-middle">
                                                    <span style='color:green;font-weight: bold'> <?php echo($detail->stoploss) ?></span>
                                                </td>

                                            </tr>
                                            <?php if ($detail->r1): ?>
                                                <tr>
                                                    <td class="align-middle">
                                                        <b>Tỷ lệ Risk/Reward:</b>
                                                    </td>
                                                    <td class="crypt-down align-middle">
                                                        <span style='color:green;font-weight: bold'> <?php echo($detail->r1) ?> / <?php echo($detail->r2) ?></span>
                                                    </td>

                                                </tr>
                                            <?php endif; ?>
                                        </tbody>
                                    </table>
                                    <div class='container-right-title'>Lịch sử đồng <?php echo($symbol); ?></div>
                                    <div class="container-history">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th scope="col">Loại tiền</th>
                                                    <th scope="col">Ngày</th>
                                                    <th scope="col">Timezone</th>
                                                </tr>
                                            </thead>
                                            <tbody class="crypt-table-hover">
                                                <?php foreach ($histories as $post): ?>
                                                    <?php
                                                    $d2 = date_create($post['date_h4']);
                                                    date_add($d2, date_interval_create_from_date_string("+4 hours"));
                                                    $d2 = date_format($d2, "Y-m-d");
                                                    ?>
                                                    <tr>
                                                        <td class="align-middle">
                                                            <img class="crypt-star pr-1" alt="star" src="<?= BASE_URL ?>/style/new/images/star.svg" width="15"> 
                                                            <a href="?ID=<?php echo($post['ID']) ?>&symbol=<?php echo($post['symbol']) ?>"><?php echo($post['symbol']) ?></a>
                                                        </td>
                                                        <td class="crypt-down align-middle">
                                                            <span class="pr-2" data-toggle="tooltip" data-placement="right" title="<?= $d2 ?>">
                                                                <span class='desc'><?php echo(date("H:i, d/m/Y", $post['close_time'] / 1000 + 1)) ?></span>
                                                            </span>
                                                        </td>
                                                        <td class="crypt-down align-middle">
                                                            UTC+7
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class='view-detail-2'>
                                    <img src="<?= BASE_URL ?>/files/images/product/<?= $formular['img'] ?>">
                                </div>

                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <!-- Content right-->
                <div class="col-md-6 col-lg-6 col-xl-3 col-xxl-3">
                    <div class="crypt-market-status mt-4" style="margin-top:0px !important;">
                        <div  style="max-height: 1012px; overflow-y: auto;">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" id="crypt-tab">
                                <li role="presentation"><a href="#usd"  class="<?= $activeUSD ?>" data-toggle="tab">USD</a></li>
                                <li role="presentation"><a href="#btc" class="<?= $activeBTC ?>" data-toggle="tab">BTC</a></li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content crypt-tab-content">
                                <div role="tabpanel" class="tab-pane <?= $activeUSD ?>" id="usd">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">Loại tiền</th>
                                                <th scope="col">Ngày</th>
                                                <th scope="col">Timezone</th>
                                            </tr>
                                        </thead>
                                        <tbody class="crypt-table-hover">
                                            <?php foreach ($posts as $p): ?>
                                                <?php foreach ($p as $post): ?>
                                                    <?php
                                                    $d2 = strtotime($post['date_h4'], "+4 hours");
                                                    ?>
                                                    <tr>
                                                        <td class="align-middle">
                                                            <img class="crypt-star pr-1" alt="star" src="<?= BASE_URL ?>/style/new/images/star.svg" width="15"> 
                                                            <a href="?ID=<?php echo($post['ID']) ?>&symbol=<?php echo($post['title']) ?>"><?php echo($post['title']) ?></a>
                                                            <?php
                                                            if ($post['date'] == date('Y-m-d')):
                                                                ?>
                                                                <sup><img src="<?= BASE_URL ?>/icon_new.gif" width='30' /></sup>
                                                            <?php endif; ?>
                                                        </td>
                                                        <td class="crypt-down align-middle">
                                                            <span class="pr-2" data-toggle="tooltip" data-placement="right" title="<?= $d2 ?>">
                                                                <span class='desc'><?php echo(date("H:i, d/m/Y", $d2)) ?></span>
                                                            </span>
                                                        </td>
                                                        <td class="crypt-down align-middle">
                                                            UTC+7
                                                        </td>

                                                    </tr>

                                                <?php endforeach; ?>
                                            <?php endforeach; ?>


                                        </tbody>
                                    </table>
                                </div>
                                <div role="tabpanel" class="tab-pane <?= $activeBTC ?>" id="btc">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">Loại tiền</th>
                                                <th scope="col">Ngày</th>
                                                <th scope="col">Timezone</th>
                                            </tr>
                                        </thead>
                                        <tbody class="crypt-table-hover">
                                            <?php foreach ($postBtcs as $p): ?>
                                                <?php foreach ($p as $post): ?>
                                                    <?php
                                                    $d2 = strtotime($post['date_h4'], "+4 hours");
                                                    ?>
                                                    <tr>
                                                        <td class="align-middle">
                                                            <img class="crypt-star pr-1" alt="star" src="<?= BASE_URL ?>/style/new/images/star.svg" width="15"> 
                                                            <a href="?ID=<?php echo($post['ID']) ?>&symbol=<?php echo($post['title']) ?>"><?php echo($post['title']) ?></a>
                                                            <?php
                                                            if ($post['date'] == date('Y-m-d')):
                                                                ?>
                                                                <sup><img src="<?= BASE_URL ?>/icon_new.gif" width='30' /></sup>
                                                            <?php endif; ?>
                                                        </td>
                                                        <td class="crypt-down align-middle">
                                                            <span class="pr-2" data-toggle="tooltip" data-placement="right" title="<?= $d2 ?>">
                                                                <span class='desc'><?php echo(date("H:i, d/m/Y", $d2)) ?></span>
                                                            </span>
                                                        </td>
                                                        <td class="crypt-down align-middle">
                                                            UTC+7
                                                        </td>

                                                    </tr>

                                                <?php endforeach; ?>
                                            <?php endforeach; ?>


                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <!--End content right-->
            </div>
        </div>
        <footer>
            <div id="footer">
                <marquee style="font-size: 20px">Giao dịch tiền kĩ thuật số mang lại lợi nhuận cao tuy nhiên cũng tiềm ẩn nhiều rủi ro. TheAlchemist chỉ cung cấp thông tin phân tích kĩ thuật, không chịu trách nhiệm về rủi ro mà nhà giao dịch gặp phải</marquee>
            </div>
        </footer>

        <script src="<?= BASE_URL ?>/style/js/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/mainh4.js"></script>
    </body>

</html>   
<?php

function smartTime($time, $father = 30, $format = 'd/m/Y') {
    if ($time === null) {
        return '';
    }

    if (!is_numeric($time))
        $time = strtotime($time);

    $diff = time() - $time;

    if ($diff > $father * 24 * 3600)
        return date($format, $time);

    if ($diff < 0) {
        return date($format, $time);
    } else if ($diff == 0) {
        return "vừa mới";
    } else if ($diff < 60) {
        return (floor($diff) . ' giây trước');
    } else if ($diff < 60 * 60) {
        return (floor($diff / 60) . ' phút trước');
    } else if ($diff < 60 * 60 * 24) {
        return (floor($diff / (60 * 60)) . ' giờ trước');
    } else if ($diff < 60 * 60 * 24 * 30) {
        $num_day = $diff / (60 * 60 * 24);
        if ($num_day < 2 && $num_day >= 1)
            return 'Hôm qua';
        if ($num_day >= 2 && $num_day < 3)
            return 'Hôm trước';
        return floor($num_day) . ' ngày trước';
    } else if ($diff < 60 * 60 * 24 * 30 * 12) {
        return (floor($diff / (60 * 60 * 24 * 30)) . ' tháng trước');
    } else {
        return (floor($diff / (60 * 60 * 24 * 30 * 12)) . ' năm trước');
    }

    return date($format, $time);
}
