<?php
$prices = $this->prices;
$formulars = $this->formulars;

$ID = $_REQUEST['ID'];
$symbol = $_REQUEST['symbol'] ?? ($this->pposts[0]['symbol'] ?? 'FILUSDT');

$dataPoints = [];
$posts = [];
$postAlls = [];
$postCurrent = [];

if ($prices) {
    foreach ($prices as $row) {
        $data = [
            'ID' => $row['ID'],
            'title' => $row['symbol'],
            'date' => $row['date'],
            'open' => round($row['open'], 4),
            'high' => round($row['high'], 4),
            'low' => round($row['low'], 4),
            'close' => round($row['close'], 4),
            'model_name' => $row['model_title'],
            'model_type' => $row['model_type'],
            'rsi' => $row['rsi'],
            'x' => $row['open_time'] / 1000,
            'y' => [round($row['open'], 4), round($row['high'], 4), round($row['low'], 4), round($row['close'], 4)]
        ];

        $postAlls[$data['title']][$data['date']] = [
            'ID' => $data['ID'],
            'date' => $data['date'],
            'open' => $data['open'],
            'high' => $data['high'],
            'low' => $data['low'],
            'close' => $data['close'],
            'model_name' => $data['model_name'],
            'model_type' => $data['model_type'],
            'rsi' => $data['rsi']
        ];


        if ($symbol == $data['title']) {
            $dataPoints[] = [
                'date' => $data['date'],
                'indexLabel' => $data['model_name'] ? $data['model_name'] : null,
                'open' => $data['open'],
                'close' => $data['close'],
                'x' => $data['x'],
                'y' => $data['y'],
            ]; //Open, hight, low. close
        }
    }
}


$posts = [];
if ($this->pposts) {
    foreach ($this->pposts as $row) {
        $data = [
            'ID' => $row['ID'],
            'title' => $row['symbol'],
            'date' => $row['date'],
            'open' => round($row['open'], 4),
            'high' => round($row['high'], 4),
            'low' => round($row['low'], 4),
            'close' => round($row['close'], 4),
            'model_name' => $row['model_title'],
            'model_type' => $row['model_type'],
            'json_details' => $row['json_details'],
            'type_id' => $row['type_id'],
            'rsi' => $row['rsi'],
            'x' => $row['open_time'] / 1000,
            'y' => [(double) $row['open'] / 1000, (double) $row['high'] / 1000, (double) $row['low'] / 1000, (double) $row['close'] / 1000]
        ];

        if ($data['ID'] == $ID && $ID) {
            $postCurrent = [
                'ID' => $data['ID'],
                'date' => $data['date'],
                'open' => $data['open'],
                'high' => $data['high'],
                'low' => $data['low'],
                'close' => $data['close'],
                'model_name' => $data['model_name'],
                'model_type' => $data['model_type'],
                'rsi' => $data['rsi'],
                'json_details' => $row['json_details'],
                'type_id' => $row['type_id']
            ];
        }

        $modelTitle = $data['model_name'];



        if (strtotime($data['date']) >= strtotime('2020-12-01')) {
            if ($modelTitle) {
                $pId = $data['ID'];
                $posts[$data['title']][$data['date']] = [
                    'ID' => $pId,
                    'title' => $data['title'],
                    'sub' => 'High: ' . (double) $data['high'] . ' - ' . 'Low: ' . (double) $data['low'],
                    //'desc' => date("d/m/Y", strtotime($data['date'])),
                    'desc' => smartTime($data['date'] . ' 00:00:00', 'd/m/Y'),
                    'date' => $data['date'],
                    'open' => $data['open'],
                    'close' => $data['close'],
                    'model_name' => $modelTitle,
                    'model_type' => $data['model_type'],
                    'rsi' => $data['rsi'],
                    'json_details' => $row['json_details'],
                    'type_id' => $row['type_id']
                ];
                $posts[$data['title']][$data['date']]['items'][3] = [
                    'date' => $data['date'],
                    'open' => $data['open'],
                    'high' => $data['high'],
                    'low' => $data['low'],
                    'close' => $data['close'],
                    'model_name' => $modelTitle,
                    'model_type' => $data['model_type'],
                    'rsi' => $data['rsi'],
                    'json_details' => $row['json_details'],
                    'type_id' => $row['type_id']
                ];

                if (!$ID && !$postCurrent) {
                    $postCurrent = [
                        'ID' => $data['ID'],
                        'date' => $data['date'],
                        'open' => $data['open'],
                        'high' => $data['high'],
                        'low' => $data['low'],
                        'close' => $data['close'],
                        'model_name' => $modelTitle,
                        'model_type' => $data['model_type'],
                        'rsi' => $data['rsi']
                    ];
                }
            }
        }
    }
}


if ($posts) {
    foreach ($posts as $s => &$p) {
        foreach ($p as $k => &$a) {
            $d = $a['date'];

            $d2 = date_create($d);
            date_add($d2, date_interval_create_from_date_string("-1 days"));
            $d2 = date_format($d2, "Y-m-d");
            $a['items'][2] = $postAlls[$s][$d2];

            $d1 = date_create($d);
            date_add($d1, date_interval_create_from_date_string("-2 days"));
            $d1 = date_format($d1, "Y-m-d");
            $a['items'][1] = $postAlls[$s][$d1];

            $d0 = date_create($d);
            date_add($d0, date_interval_create_from_date_string("-3 days"));
            $d0 = date_format($d0, "Y-m-d");
            $a['items'][0] = $postAlls[$s][$d0];
        }
    }
    unset($a, $p);
}
?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Market Trading</title>
        <!-- stylesheets -->
        <link href="<?= BASE_URL ?>/style/assets/bootstrap.min.css" rel="stylesheet">
        <link href="<?= BASE_URL ?>/style/assets/style.css" rel="stylesheet">
        <link href="<?= BASE_URL ?>/style/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    </head><script type="text/javascript" src="<?= BASE_URL ?>/style/assets/js/jquery-1.11.1.min.js"></script>

    <script>
        window.onload = function () {
            var dps = [];
            var chart = new CanvasJS.Chart("chartContainer", {
                title: {
                    text: 'Giá đồng ' + '<?php echo($symbol) ?>'
                },
                subtitles: [{
                        text: '<?php echo($symbol) ?>'
                    }],
                dataPointWidth: 12,
                dataPointHeight: 30,
                zoomEnabled: true,
                zoomType: "y",
                animationEnabled: true,
                theme: "light2", // "light1", "light2", "dark1", "dark2"
                exportEnabled: true,
                legend: {
                    fontSize: 0,
                    horizontalAlign: "right",
                    verticalAlign: "center",
                    yValueFormatString: "$#,##0.00"
                },
                axisX: {
                    valueFormatString: "DD/MM"
                },
                axisY: {
                    title: "Price",
                    //interval: 0.0005,
                    prefix: "$"
                },
                data: [
                    {
                        type: "candlestick",
                        xValueType: "dateTime",
                        yValueFormatString: "#,##0.0",
                        xValueFormatString: "DD/MM",
                        showInLegend: true,
                        risingColor: "rgb(47,166,154)",
                        fallingColor: "rgb(237,85,84)",
                        name: "Tỷ giá",
                        dataPoints: dps
                    }
                ]
            });
            var result =<?php echo(json_encode($dataPoints)) ?>;
            for (var i = 0; i < result.length; i++) {
                var item = {
                    x: new Date(result[i].date),
                    y: result[i].y,
                    color: result[i].open < result[i].close ? "rgb(47,166,154)" : "rgb(237,85,84)"
                };

                if (result[i].indexLabel) {
                    item.indexLabel = result[i].indexLabel;
                    item.indexLabelFontSize = '10';
                    item.indexLabelFontColor = result[i].open < result[i].close ? "rgb(47,166,154)" : "rgb(237,85,84)";
                    //item.indexLabelFontWeight = 'bolder';
                    item.indexLabelMaxWidth = 80;
                    item.indexLabelWrap = true;
                    item.indexLabelPlacement = "outside";
                    item.indexLabelOrientation = "vertical";
                }

                dps.push(item);
            }
            chart.render();

            chart.render();


        }
    </script>
</head>
<body>
    <div id="container">
        <div id ='container-left'>
            <div id="chartContainer" style="height: 370px; width: 100%;"></div>
            <div id="view-detail">
                <?php
                if ($postCurrent) :
                    $dCurrent = $postCurrent['date'];
                    $postCurrent = $posts[$symbol][$dCurrent];

                    $detail = [];
                    if ($postCurrent) {
                        $detail = json_decode($postCurrent['json_details']);
                        $formular = $formulars[$postCurrent['type_id']];
                    }
                    ?>
                    <div class='container-right-title'>Chi tiết giá đồng <?php echo($symbol); ?> ngày <?php echo(date("d/m/Y", strtotime("+1 day" . $dCurrent))) ?></div>
                    <div class='view-detail-1'>
                        <div style='padding:10px'><b>Type:</b><span style='color:green;font-weight: bold'> <?php echo($postCurrent['model_name']) ?></span></div>
                        <div style='padding:10px'><b>Entry Zone:</b><span style='color:green;font-weight: bold'> <?php echo($detail->buylong) ?></span></div>
                        <div style='padding:10px'><b>Target_1:</b><span style='color:green;font-weight: bold'> <?php echo($detail->target1) ?></span></div>
                        <div style='padding:10px'><b>Target_2:</b><span style='color:green;font-weight: bold'> <?php echo($detail->target2) ?></span></div>
                        <?php/* if ($detail->target3): ?>
                            <div style='padding:10px'><b>Target_3:</b><span style='color:green;font-weight: bold'> //<?php echo($detail->target3) ?></span></div>
                        <?php endif; */?>

                        <div style='padding:10px'><b>Stoplost:</b> <span style='color:green;font-weight: bold'><?php echo($detail->stoploss) ?></span></div>
                        <?php if ($detail->r1): ?>
                            <div style='padding:10px'><b>Tỷ lệ R/R:</b> <span style='color:green;font-weight: bold'><?php echo($detail->r1) ?> / <?php echo($detail->r2) ?></span></div>
                        <?php endif; ?>
                    </div>
                    <div class='view-detail-2'>
                        <img src="<?= BASE_URL ?>/files/images/product/<?= $formular['img'] ?>">
                    </div>

                <?php endif; ?>
            </div>
        </div>
        <div id ='container-right'>
            <div class='container-right-title'>Mã giao dịch</div>
            <div class='container-right-content'>
                <ul class='container-right-title-ul'>
                    <?php foreach ($posts as $p): ?>
                        <?php foreach ($p as $post): ?>
                            <li class='container-right-title-li'>
                                <a href="?ID=<?php echo($post['ID']) ?>&symbol=<?php echo($post['title']) ?>" style='font-size:20px;'><?php echo($post['title']) ?></a>
                                <?php
                                $d2 = date_create($post['date']);
                                date_add($d2, date_interval_create_from_date_string("+1 days"));
                                $d2 = date_format($d2, "Y-m-d");
                                if ($post['date'] == date('Y-m-d') || $d2 == date('Y-m-d')):
                                    ?>
                                    <sup><img src="<?= BASE_URL ?>/icon_new.gif" width='40' /></sup>
                                <?php endif; ?>
                                <br>
                                <span class='desc'><?php echo(date("d/m/Y", strtotime($d2))) ?></span>
                                <!--                                <br>
                                                                <span class='desc'><?php echo(round($post['rsi'], 4)) ?></span>-->
                            </li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div id="footer">
        <marquee style="font-size: 20px">Giao dịch tiền kĩ thuật số mang lại lợi nhuận cao tuy nhiên cũng tiềm ẩn nhiều rủi ro. TheAlchemist chỉ cung cấp thông tin phân tích kĩ thuật, không chịu trách nhiệm về rủi ro mà nhà giao dịch gặp phải</marquee>
    </div>
    <script src="<?= BASE_URL ?>/style/assets/js/canvasjs.js"></script>

</body>

</html>  
<?php

function smartTime($time, $father = 30, $format = 'd/m/Y') {
    if ($time === null) {
        return '';
    }

    if (!is_numeric($time))
        $time = strtotime($time);

    $diff = time() - $time;

    if ($diff > $father * 24 * 3600)
        return date($format, $time);

    if ($diff < 0) {
        return date($format, $time);
    } else if ($diff == 0) {
        return "vừa mới";
    } else if ($diff < 60) {
        return (floor($diff) . ' giây trước');
    } else if ($diff < 60 * 60) {
        return (floor($diff / 60) . ' phút trước');
    } else if ($diff < 60 * 60 * 24) {
        return (floor($diff / (60 * 60)) . ' giờ trước');
    } else if ($diff < 60 * 60 * 24 * 30) {
        $num_day = $diff / (60 * 60 * 24);
        if ($num_day < 2 && $num_day >= 1)
            return 'Hôm qua';
        if ($num_day >= 2 && $num_day < 3)
            return 'Hôm trước';
        return floor($num_day) . ' ngày trước';
    } else if ($diff < 60 * 60 * 24 * 30 * 12) {
        return (floor($diff / (60 * 60 * 24 * 30)) . ' tháng trước');
    } else {
        return (floor($diff / (60 * 60 * 24 * 30 * 12)) . ' năm trước');
    }

    return date($format, $time);
}
