<!DOCTYPE html>
<html>
  <head>
  <title>Al-Trade-Subsysterm</title>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--font-->
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/font.css">
    <!--style--> 
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/theme.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/style-home.css">  
     <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/aos.css">
     <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/swiper.min.css" >
     <!--altrade_styles-->
     <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/al-trade.css">

     <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TheAlchemist</title>
        <link rel="shortcut icon" href="<?= BASE_URL ?>/favicon.ico" />
        
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/new/css/style.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/mydashboard.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/knowledge.css">

     <script src="<?= BASE_URL ?>/style/js/jquery-3.6.0.min.js"></script>
     <script src="<?= BASE_URL ?>/style/js/social.js"></script>

  </head>
 
<body>

<!--header-->
<div class="header">
	<div class="container">
            <a href="http://thealchemist.ai/en" class="logo">The Alchemist</a>
            <ul class="menu-top">
                <li>
                	<a href="http://thealchemist.ai/en/trade2" >Al-Trade</a>
                	
                </li>
                <li><a href="http://thealchemist.ai/en/social" >Social</a></li>
                <li>
                	<a  href="http://thealchemist.ai/en/academy">Academy</a>
                    
                </li>
                <li>
                	<a href="http://thealchemist.ai/en/news" >News</a>
                   
                </li>
                
            </ul>
            <div class="head-right">
                <a href="http://thealchemist.ai/en/login" class="btn-login">Login</a>
                <button class="btn-connect-wallet" data-toggle="modal" data-target="#connect-wallet">Connect Wallet</button>
            </div>
    </div>
</div>
<!--end header-->

<!--Al-trade_body-->
<div class="wapper">
        <!--Notice Box--> 
        <div class="container"> 
            <div class="Social-body">
                <!--left-menu--> 
                <div class="left-menu">
                    <div class="profile_user">
                        <div class="avatar">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                        </div>
                        <a>Alex Nguyen</a>
                    </div>
                    
                        <ul class="ul">
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/newsfeed-icon.svg">
                                <a class="subsys-name">
                                    News Feed
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/myprofile-icon.svg">
                                <a class="subsys-name">
                                    My Profile
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/group-icon.svg">
                                <a class="subsys-name">
                                    Group
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/marketplace-icon.svg">
                                <a class="subsys-name">
                                    Marketplace
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/formula-icon.svg">
                                <a class="subsys-name">
                                My Formula
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/dashboard-icon-white.svg">
                                <a class="subsys-name">
                                    Dashboard
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/leaderboard-icon.svg">
                                <a class="subsys-name">
                                    Leaderboard
                                </a>
                            </li>
                            
                        </ul>
                    
                </div>
                <!--main-->
                <div class="social-main">
                    <div class="main-top">
                        <div class="status-box">
                            <div class="main-avatar">
                                <i class="avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                    <a><input class="main-input-post" name="" value="" id= "" type="text" placeholder="User-name, What’s on your mind?" /></a>
                                </i> 
                            </div>
                            <div class="button-box">
                                <div type="button" class="button-box-photo">
                                  <img class="image" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/photo.svg">
                                </div>
                                <div type="button" class="button-box-cam">
                                    <img class="image" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/camera.svg">
                                </div>
                                <div type="button" class="button-box-plus">
                                    <img class="image" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/plus.svg">
                                </div>
                                <div class="btn-post"><a>Post</a></div>
                            </div>
                        </div>
                    </div>
                
                    <div class="btn-box">
                        <a class="btn">All</a>
                        <a class="btn">Groups</a>
                        <a class="btn">Likes</a>
                    </div>
                    <div class="box-posted">
                        <div class="top">
                                <div class="main-avatar">
                                        <i class="avatar">
                                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                        </i> 
                                </div>
                                <div class="user-name">
                                    <a>Username</a>
                                </div>
                                <div class="time-posted">
                                    <a>5 minutes ago</a>
                                </div>
                                <div type="button" class="btn-drop-down">
                                        <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/three-dots.svg">
                                        
                                </div>
                        </div>       
                        
                        <div class="content-posted">
                                <a>Whether its a driving tour, leaf viewing is a great way to spend a fall vacation 😂 </a>
                        </div>
                        <div class="box-photo">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/web2x.png">
                        </div>
                        <div class="border-line">
                            
                        </div>       
                        <div class="posted-likes">
                                <a class="btn-likes"> 
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/heart.svg">
                                326
                                </a>
                                <a class="btn-likes"> 
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/comment.svg">
                                326
                                </a>
                                <a class="btn-likes"> 
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/share.svg">
                                326
                                </a>
                        </div>
                        <div class="comment-box">
                                <div class="main-avatar">
                                        <i class="avatar">
                                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                        </i> 
                                </div>
                                    <div class="comment-text">
                                        <a><input class="main-input-post" name="" value="" id= "" type="text" placeholder="Write your comment..." /></a>
                                       
                                    </div>
                        </div>
                        
                    </div>
                </div>
                <!--right-menu--> 
                <div class="social-right">
                    <div class="top-search">
                        <i type="button" class="search-label">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/search-icon.svg">
                        </i> 
                        
                        <a><input class="search-box" name="" value="" id= "" type="text" placeholder="Search" /></a>
                        
                        <div type="button" class="close-search">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/close-icon.svg">
                        </div>
                    </div>
                    <div class="button-box-right">
                        <i type="button" class="group-button">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/group-black-icon.svg">
                        </i> 
                        <i type="button" class="group-button">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/notice-blue-icon.svg">
                        </i> 
                        <i type="button" class="group-button">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/comment-icon.svg">
                        </i> 
                        <i type="button" class="group-button">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/setting-icon.svg">
                        </i> 
                    </div>

                    <!--Top-rank -->

                    <div class="top-rank">
                        <div class="title-box-right">
                           <a class="head-title">Top Traders of the month</a>
                        </div>
                        <div class="top-rank-sub">
                            <div class="top-rank-sub rank-content">
                                <i class="rank-content-avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                </i>
                                <div class="right-user-name">
                                    <a>Alex Nguyen
                                    <i class="right-user-label">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/rank-top-1-right.svg">
                                    </i>
                                    </a>
                                </div>

                                <div class="user-rank-index">
                                    <img class="win-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trend-up-right.svg">
                                    <a class="win-text">
                                        Win rate: <span>75%</span>
                                    </a>
                                    <img class="roi-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/roi-right.svg">
                                    <a class="roi-text">
                                        ROI: <span>75%</span>
                                    </a>
                                    
                                </div>
                                <div class="reward">
                                <img class="cup-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trophy-cup-silhouette 1.svg">
                                    <a class="win-text">
                                        Reward: <span>1.000 AAI</span>
                                    </a>
                                    
                                </div>
                                <div class="box-btn-follow">
                                    <div type="button" class="btn-follow">
                                        <a hrerf="">Follow</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                        <div class="top-rank-sub">
                            <div class="top-rank-sub rank-content">
                                <i class="rank-content-avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                </i>
                                <div class="right-user-name">
                                    <a>Alex Nguyen
                                    <i class="right-user-label">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/rank-top-2-right.svg">
                                    </i>
                                    </a>
                                </div>

                                <div class="user-rank-index">
                                    <img class="win-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trend-up-right.svg">
                                    <a class="win-text">
                                        Win rate: <span>70%</span>
                                    </a>
                                    <img class="roi-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/roi-right.svg">
                                    <a class="roi-text">
                                        ROI: <span>70%</span>
                                    </a>
                                    
                                </div>
                                <div class="reward">
                                <img class="cup-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trophy-cup-silhouette 1.svg">
                                    <a class="win-text">
                                        Reward: <span>800 AAI</span>
                                    </a>
                                    
                                </div>
                                <div class="box-btn-follow">
                                    <div type="button" class="btn-follow">
                                        <a hrerf="">Follow</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                        <div class="top-rank-sub">
                            <div class="top-rank-sub rank-content">
                                <i class="rank-content-avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                </i>
                                <div class="right-user-name">
                                    <a>Alex Nguyen
                                    <i class="right-user-label">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/rank-top-3-right.svg">
                                    </i>
                                    </a>
                                </div>

                                <div class="user-rank-index">
                                    <img class="win-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trend-up-right.svg">
                                    <a class="win-text">
                                        Win rate: <span>65%</span>
                                    </a>
                                    <img class="roi-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/roi-right.svg">
                                    <a class="roi-text">
                                        ROI: <span>65%</span>
                                    </a>
                                    
                                </div>
                                <div class="reward">
                                <img class="cup-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trophy-cup-silhouette 1.svg">
                                    <a class="win-text">
                                        Reward: <span>600 AAI</span>
                                    </a>
                                    
                                </div>
                                <div type="button" class="box-btn-follow">
                                    <div class="btn-follow">
                                        <a hrerf="">Follow</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                        
                    
                    </div>
                    <!--Top-distibution -->   
                    <!--
                    <div class="month-rank">
                        <div class="title-box-right-2">
                           <a class="head-title">Top Contributors of the Month</a>
                        </div>
                        <div class="month-rank top-rank-sub-2"></div>
                    </div>
                    --> 
                    <div class="month-rank">
                        <div class="title-box-right">
                           <a class="head-title">Top Contributors of the Month</a>
                        </div>
                        <div class="top-rank-sub">
                            <div class="top-rank-sub rank-content">
                                <i class="rank-content-avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                </i>
                                <div class="right-user-name">
                                    <a>Alex Nguyen
                                    <i class="right-user-label">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/rank-top-1-right.svg">
                                    </i>
                                    </a>
                                </div>

                                <div class="user-rank-index">
                                    
                                    <a>
                                        @alexnguyen
                                    </a>
    
                                    
                                </div>
                                <div class="reward">
                                <img class="cup-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trophy-cup-silhouette 1.svg">
                                    <a class="win-text">
                                        Reward: <span>1.000 AAI</span>
                                    </a>
                                    
                                </div>
                                <div class="box-btn-follow">
                                    <div type="button" class="btn-follow">
                                        <a hrerf="">Follow</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                        <div class="top-rank-sub">
                            <div class="top-rank-sub rank-content">
                                <i class="rank-content-avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                </i>
                                <div class="right-user-name">
                                    <a>Alex Nguyen
                                    <i class="right-user-label">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/rank-top-2-right.svg">
                                    </i>
                                    </a>
                                </div>

                                <div class="user-rank-index">
                                    <a>
                                        @alexnguyen
                                    </a>
                                    
                                </div>
                                <div class="reward">
                                <img class="cup-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trophy-cup-silhouette 1.svg">
                                    <a class="win-text">
                                        Reward: <span>800 AAI</span>
                                    </a>
                                    
                                </div>
                                <div class="box-btn-follow">
                                    <div type="button" class="btn-follow">
                                        <a hrerf="">Follow</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                        <div class="top-rank-sub">
                            <div class="top-rank-sub rank-content">
                                <i class="rank-content-avatar">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                                </i>
                                <div class="right-user-name">
                                    <a>Alex Nguyen
                                    <i class="right-user-label">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/rank-top-3-right.svg">
                                    </i>
                                    </a>
                                </div>

                                <div class="user-rank-index">
                                    <a>
                                        @alexnguyen
                                    </a>
                                    
                                </div>
                                <div class="reward">
                                <img class="cup-label" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/trophy-cup-silhouette 1.svg">
                                    <a class="win-text">
                                        Reward: <span>600 AAI</span>
                                    </a>
                                    
                                </div>
                                <div type="button" class="box-btn-follow">
                                    <div class="btn-follow">
                                        <a hrerf="">Follow</a>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                        
                    
                    </div>
                    <div class="trending-box">
                        <div class="trending-title">
                            <a href="" class="">
                            Trends for you
                            </a>
                        </div>
                        <div class="trending-content-box">
                            <div class="trending-content">
                                <div class="trend-text1">
                                    <a>Business & finance • Trending</a>
                                </div>
                                <div class="coin-name-1">
                                    <a>#BTC</a>
                                </div>
                                <div class="search-info">
                                    <a>22.9K Search</a>
                                </div>

                            </div>
                            <div class="trending-content">
                                <div class="trend-text1">
                                    <a>Business & finance • Trending</a>
                                </div>
                                <div class="coin-name-1">
                                    <a>#BUSD</a>
                                </div>
                                <div class="search-info">
                                    <a>12.8K Search</a>
                                </div>
                            </div>
                            <div class="trending-content">
                            <div class="trend-text1">
                                    <a>Business & finance • Trending</a>
                                </div>
                                <div class="coin-name-1">
                                    <a>#USDT</a>
                                </div>
                                <div class="search-info">
                                    <a>10.6K Search</a>
                                </div>
                            </div>       
                        </div>
                    </div>

                </div> 
            </div>        
                                <!--End-Trading-Strategy-->
            
                                <!--end_al_trade-->
        </div>
</div>



        <!--footer-->
      
<div class="footer">
	<div class="container">
    	<div class="box-left">
            <a href="#" class="logo-ft"></a>
            <p class="des">
            	Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics.
            </p>
            <div class="box-network">
            	<h2 class="title">Social Media</h2>
                <div class="list">
                	 <a href="#" class="icon wt">Twitter</a>
                      <a href="#" class="icon m">M</a>
                      <a href="#" class="icon youtobe">Youtube</a>
                	<a href="#" class="icon telegam">Telegam</a>
                    <a href="#" class="icon fb">Facebook</a>
                </div>
            </div>
        </div>
        <div class="box-right">
              <div class="item">
              	<h2 class="title">About Us</h2>
                <a href="#" class="alink">Whitepaper</a>
                <a href="#" class="alink">Business Contact </a>
                <a href="#" class="alink">Careers</a>
              </div> 
              <div class="item">
              	<h2 class="title">Products</h2>
                <a href="#" class="alink">Al-Trade</a>
                <a href="#" class="alink">Dashboard</a>
                <a href="#" class="alink">Social</a>
                <a href="#" class="alink">Marketplace<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Box<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Launchpad<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Trend Spotter<span class="item-comingson">Coming Soon</span> </a>
              </div> 
              <div class="item">
              	<h2 class="title">Learn</h2>
                <a href="#" class="alink">Guide</a>
                <a href="#" class="alink">Academy</a>
                <a href="#" class="alink">News</a>
              </div> 
              <div class="item">
              	<h2 class="title">Support </h2>
                <a href="#" class="alink">Feedback</a>
                <a href="#" class="alink">Support Center</a>
                <a href="#" class="alink">Request</a>
              </div> 
        </div>
        <div class="box-conpy-right">
        	@2022 The Alchemist - All Rights Reserved
            
        </div>
    </div>
</div> 
    
    <!--popup connect wallet-->
    <div class="modal fade" id="connect-wallet" >
        <div class="modal-dialo box-connect-wallet">
            <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
                    <h4 class="modal-title" id="myModalLabel">Import Your Wallet</h4>
                <div class="list">
                    <div class="row">
                        <div class="col-6">
                            <div class="item">
                                <i class="icon MetaMask"></i>
                                <h3 class="title"><a href="#">MetaMask</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon WalletConnect"></i>
                                <h3 class="title"><a href="#">WalletConnect</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon BinanceChainWallet"></i>
                                <h3 class="title"><a href="#">Binance Chain Wallet</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon TrustWallet"></i>
                                <h3 class="title"><a href="#">TrustWallet</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon Coin98Wallet"></i>
                                <h3 class="title"><a href="#">Coin98 Wallet</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon HoubiWallet"></i>
                                <h3 class="title"><a href="#">Houbi Wallet</a></h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="icon-back-top"><i class="icon-up-open-1"></i></a>
    <script src="js/jquery-1.11.0.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.min.js" type="text/javascript"></script>
    <script src="js/defaul.js" type="text/javascript"></script>
    <script src="js/aos.js" type="text/javascript"></script>
    <script>
             AOS.init();
        </script>
        <script src="<?= BASE_URL ?>/style/js/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/mainh4.js"></script>
        <script  type="text/javascript">
            var studies = <?php echo json_encode($study); ?>;
            if (document.getElementById('crypt-candle-chart')) {
                new TradingView.widget(
                        {
                            "autosize": true,
                            "symbol": "<?= $symbol ?>",
                            "interval": "<?php echo($interval); ?>",
                            "timezone": "Europe/Greenwich",
                            "theme": "Light",
                            "style": "1",
                            "locale": "en_EN",
                            "toolbar_bg": "rgba(255, 255, 255, 1)",
                            "enable_publishing": false,
                            "allow_symbol_change": true,
                            "show_popup_button": true,
                            "popup_width": "1000",
                            "popup_height": "1000",
                            "withdateranges": true,
                            "container_id": "crypt-candle-chart",
                            "studies_overrides": {
                                "rsi.rsi.plot.color": "#2196f3",
                                "rsi.level.0": 20,
                                "rsi.level.1": 80
                            },
                            "studies": studies
                        }
                );
            }
        </script>
    </body>
    </html>