
?>
<!DOCTYPE html>
<html>
  <head>
  
  <title>My Formula</title>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--font-->
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/font.css">
    <!--style--> 
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/theme.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/style-home.css">  
     <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/aos.css">
     <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/swiper.min.css" >
     <!--maydashboard_styles-->
     
     <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/mydashboard.css">
     <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TheAlchemist</title>
        <link rel="shortcut icon" href="<?= BASE_URL ?>/favicon.ico" />
        
       
       
       

     <script src="<?= BASE_URL ?>/style/js/jquery-3.6.0.min.js"></script>
     <script src="<?= BASE_URL ?>/style/js/social.js"></script>
    <!--chart.js--> 
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
     <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
     <script src="https://code.highcharts.com/highcharts.js"></script>
     <script src="https://code.highcharts.com/modules/accessibility.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
  </head>

<body>

<!--header-->
<div class="header">
	<div class="container">
            <a href="http://thealchemist.ai/en" class="logo">The Alchemist</a>
            <ul class="menu-top">
                <li>
                	<a href="http://thealchemist.ai/en/trade2" >Al-Trade</a>
                	
                </li>
                <li><a href="http://thealchemist.ai/en/social" >Social</a></li>
                <li>
                	<a  href="http://thealchemist.ai/en/academy">Academy</a>
                    
                </li>
                <li>
                	<a href="http://thealchemist.ai/en/news" >News</a>
                   
                </li>
                
            </ul>
            <div class="head-right">
                <a href="http://thealchemist.ai/en/login" class="btn-login">Login</a>
                <button class="btn-connect-wallet" data-toggle="modal" data-target="#connect-wallet">Connect Wallet</button>
            </div>
    </div>
</div>
<!--end header-->

<!--dashboard_body-->
<div class="wapper">
        <!--Notice Box--> 
        <div class="container"> 
            <div class="mydashboard-body">
                <!--left-menu--> 
                <div class="left-menu">
                    <div class="profile_user">
                        <div class="avatar">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                        </div>
                        <a>Alex Nguyen</a>
                    </div>
                    
                        <ul class="ul">
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/newsfeed-icon.svg">
                                <a class="subsys-name">
                                    News Feed
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/myprofile-icon.svg">
                                <a class="subsys-name">
                                    My Profile
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/group-icon.svg">
                                <a class="subsys-name">
                                    Group
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/marketplace-icon.svg">
                                <a class="subsys-name">
                                    Marketplace
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/formula-icon.svg">
                                <a class="subsys-name">
                                My Formula
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/dashboard-icon-white.svg">
                                <a class="subsys-name">
                                    Dashboard
                                </a>
                            </li>
                            <li class="li">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/leaderboard-icon.svg">
                                <a class="subsys-name">
                                    Leaderboard
                                </a>
                            </li>
                            
                        </ul>
                    
                </div>
                <!--main-->
                
                <div class="mydashboard-body dashboard-main">
                    <div class="top-main">
                        <div class="avartar-dashboard">
                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/big-avatar.png">
                        </div>
                        <div class="top-main-sub">
                            <div class="user-fullname">
                                <a>Alex Nguyen</a>
                            </div>
                            <div class="btn-edit-profile">
                                    <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/edit-profile.svg">
                                <a class="text-content-btn" href="#">
                                <b>Edit Profile</b>
                                </a>
                            </div>
                        </div>
                        <div class="perfomation-box">
                            <div class="winratebox">
                                <div class="index-name">
                                    <a>
                                        Win Rate
                                    </a>
                                </div>
                                <div class="index-box">
                                    <div class="index"> 
                                        <a style="color: #00BD46;">
                                        75%
                                    </a>
                                    </div>
                                </div>
                            </div>
                            <div class="win-loss">
                                <div class="index-name">
                                    <a>
                                        Win - Loss Ratio
                                    </a>
                                </div>
                                <div class="index-box">
                                    <div class="index"> 
                                        <a style="color: #F59E0B;">
                                        16%
                                    </a>
                                    </div>
                                </div>
                            </div>
                            <div class="skill-book">
                                <div class="index-name">
                                    <a>
                                        Skill Book Revenue
                                    </a>
                                </div>
                                <div class="index-box">
                                    <div class="index"> 
                                        <a style="color: #00BCD4;">
                                        6789 AAI 
                                    </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="about-text">
                            <a>About:</a>
                        </div>
                        <div class="text-note">
                            <a>
                            Lorem ipsum dolor sit amet,
                            consectetur adipiscing elit. Lorem ipsum dolor sit amet.
                            </a>
                        </div>
                    </div>
                    <!--setting-->
                    <div class="second-top-box">
                        AAA
                    </div>
                    <!--
                        <div class="time-frame-box">
                            <input name="time" type="radio" value="week" />
                            <a>Week</a>
                            <input name="time" type="radio" value="month" />
                            <a>Month</a>
                            <input name="time" type="radio" value="year" />
                            <a>Year</a>
                        </div>
                    -->
                    <!--perfomation
                    <div class="box-perfomation">
                        <div class="gain-box">
                            <div class="icon-up">
                                <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/gain-icon.svg">
                            </div>
                            <div class="box-name">
                                <a>GAIN</a>
                            </div>
                            <div class="index-box">
                                <a>26</a>
                            </div>
                            <div class="icon-bottom">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/arrow-up-icon.svg">
                            </div>
                            <div class="index-rate">
                                <a>+12%</a>
                            </div>
                            <div class="since">
                                <a>Since last week</a>
                            </div>
                        </div>
                        <div class="gain-box1">
                            <div class="icon-up">
                                <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/loss-icon1.svg">
                            </div>
                            <div class="box-name">
                                <a>LOSS</a>
                            </div>
                            <div class="index-box">
                                <a>26</a>
                            </div>
                            <div class="icon-bottom">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/arrow-down.svg">
                            </div>
                            <div class="index-rate">
                                <a>-12%</a>
                            </div>
                            <div class="since">
                                <a>Since last week</a>
                            </div>
                        </div>
                        <div class="gain-box2">
                            <div class="icon-up">
                                <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/processing-icon.svg">
                            </div>
                            <div class="box-name">
                                <a>PROCESSING</a>
                            </div>
                            <div class="index-box">
                                <a>26</a>
                            </div>
                            <div class="icon-bottom">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/arrow-up-icon.svg">
                            </div>
                            <div class="index-rate">
                                <a>+12%</a>
                            </div>
                            <div class="since">
                                <a>Since last week</a>
                            </div>
                        </div>
                        <div class="gain-box3">
                            <div class="icon-up">
                                 <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/toltalorder-icon.svg">
                            </div>
                            <div class="box-name">
                                <a>TOTAL ORDERS</a>
                            </div>
                            <div class="index-box">
                                <a>26</a>
                            </div>
                            <div class="icon-bottom">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/arrow-up-icon.svg">
                            </div>
                            <div class="index-rate">
                                <a>+12%</a>
                            </div>
                            <div class="since">
                                <a>Since last week</a>
                            </div>
                        </div>
                        <div class="gain-box4">
                            <div class="icon-up">
                                <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/totalprofit-icon.svg">
                            </div>
                            <div class="box-name">
                                <a>TOTAL PROFIT</a>
                            </div>
                            <div class="index-box">
                                <a>26</a>
                            </div>
                            <div class="icon-bottom">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/arrow-up-icon.svg">
                            </div>
                            <div class="index-rate">
                                <a>+12%</a>
                            </div>
                            <div class="since">
                                <a>Since last week</a>
                            </div>
                        </div>
                        <div class="gain-box5">
                            <div class="icon-up">
                                <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/avgroi-icon.svg">
                            </div>
                            <div class="box-name">
                                <a>AVERAGE ROI</a>
                            </div>
                            <div class="index-box">
                                <a>26</a>
                            </div>
                            <div class="icon-bottom">
                                <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/arrow-up-icon.svg">
                            </div>
                            <div class="index-rate">
                                <a>+12%</a>
                            </div>
                            <div class="since">
                                <a>Since last week</a>
                            </div>
                        </div>
                    </div>
                    --> 
                    <!--chart
                    <div class="chart-frame">
                        <div class="chart-left">
                            <div class="line-chart">
                            
                            <canvas id="myChart" style="width:450px;height: 396px;"></canvas>

                                        <script>
                                            
                                        const xValues = [1,2,3,4,5,6,7];

                                        new Chart("myChart", {
                                        type: "line",
                                        
                                        data: {
                                            labels: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
                                            datasets: [{ 
                                            data: [1,3,5,7,8,6,4],
                                            borderColor: "#00BD46",
                                            fill: false
                                            }, { 
                                            data: [3,6,4,2,5,8,9],
                                            borderColor: "#CC0001",
                                            fill: false
                                            }, { 
                                            data: [4,5,7,9,3,2,6],
                                            borderColor: "#F59E0B",
                                            fill: false
                                            }]
                                        },
                                        options: {
                                            legend: {display: false}
                                        }
                                        });
                                        </script>
                                     
                            </div>    
                        </div>
                        <div class="chart-right">
                            <div class="doughnut-chart">
                                <canvas id="ROI" style="width:300px;height: 300px;"></canvas>
                                <script>
                                    const ctx = document.getElementById('ROI');

                                    new Chart(ctx, {
                                        type: 'doughnut',
                                        data: {
                                         /** 
                                        labels: ['Gain', 'Loss', 'Processing'],
                                        */
                                        datasets: [{
                                            label: ' of orders',
                                            data: [300, 50, 100],
                                            backgroundColor: [
                                                '#00BD46',
                                                '#CC0001',
                                                '#F59E0B'
                                            ],
                                            borderWidth: 6
                                        }]
                                        },
                                        options: {
                                        scales: {
                                            y: {
                                            beginAtZero: true
                                            }
                                        }
                                        }
                                    });
                                </script>
                            </div>
                            
                           
                        </div>
                    </div>
                    <div class="table-name">
                        <a href="" class="">
                            Trading Skill Book Sales
                        </a>
                    </div>
                    <div class="trading-book-chart">
                    <img class="img" src="<?= BASE_URL ?>/style/css/new-images/icon-coin/bookchart.png">
                                -->                 
                               
                    </div>
                </div>
            </div>        
                                <!--End-Trading-Strategy-->
            
                                <!--end_al_trade-->
        </div>
</div>



        <!--footer-->
      <!--
<div class="footer">
	<div class="container">
    	<div class="box-left">
            <a href="#" class="logo-ft"></a>
            <p class="des">
            	Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics.
            </p>
            <div class="box-network">
            	<h2 class="title">Social Media</h2>
                <div class="list">
                	 <a href="#" class="icon wt">Twitter</a>
                      <a href="#" class="icon m">M</a>
                      <a href="#" class="icon youtobe">Youtube</a>
                	<a href="#" class="icon telegam">Telegam</a>
                    <a href="#" class="icon fb">Facebook</a>
                </div>
            </div>
        </div>
        <div class="box-right">
              <div class="item">
              	<h2 class="title">About Us</h2>
                <a href="#" class="alink">Whitepaper</a>
                <a href="#" class="alink">Business Contact </a>
                <a href="#" class="alink">Careers</a>
              </div> 
              <div class="item">
              	<h2 class="title">Products</h2>
                <a href="#" class="alink">Al-Trade</a>
                <a href="#" class="alink">Dashboard</a>
                <a href="#" class="alink">Social</a>
                <a href="#" class="alink">Marketplace<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Box<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Launchpad<span class="item-comingson">Coming Soon</span></a>
                <a href="#" class="alink">Trend Spotter<span class="item-comingson">Coming Soon</span> </a>
              </div> 
              <div class="item">
              	<h2 class="title">Learn</h2>
                <a href="#" class="alink">Guide</a>
                <a href="#" class="alink">Academy</a>
                <a href="#" class="alink">News</a>
              </div> 
              <div class="item">
              	<h2 class="title">Support </h2>
                <a href="#" class="alink">Feedback</a>
                <a href="#" class="alink">Support Center</a>
                <a href="#" class="alink">Request</a>
              </div> 
        </div>
        <div class="box-conpy-right">
        	@2022 The Alchemist - All Rights Reserved
            
        </div>
    </div>
</div> 
    --> 
    <!--popup connect wallet-->
    <div class="modal fade" id="connect-wallet" >
        <div class="modal-dialo box-connect-wallet">
            <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
                    <h4 class="modal-title" id="myModalLabel">Import Your Wallet</h4>
                <div class="list">
                    <div class="row">
                        <div class="col-6">
                            <div class="item">
                                <i class="icon MetaMask"></i>
                                <h3 class="title"><a href="#">MetaMask</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon WalletConnect"></i>
                                <h3 class="title"><a href="#">WalletConnect</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon BinanceChainWallet"></i>
                                <h3 class="title"><a href="#">Binance Chain Wallet</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon TrustWallet"></i>
                                <h3 class="title"><a href="#">TrustWallet</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon Coin98Wallet"></i>
                                <h3 class="title"><a href="#">Coin98 Wallet</a></h3>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="item">
                                <i class="icon HoubiWallet"></i>
                                <h3 class="title"><a href="#">Houbi Wallet</a></h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="icon-back-top"><i class="icon-up-open-1"></i></a>
    <script src="js/jquery-1.11.0.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.min.js" type="text/javascript"></script>
    <script src="js/defaul.js" type="text/javascript"></script>
    <script src="js/aos.js" type="text/javascript"></script>
    <script>
             AOS.init();
        </script>
        <script src="<?= BASE_URL ?>/style/js/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/mainh4.js"></script>
                               
        
                                    
    </body>
    </html>