<footer>
    <div class="row footer">
        <div class="althem-footer">
            <div class="col-3 althem-left">
                <div class="althem-left-img">
                    <img src="<?= BASE_URL ?>/style/img/logo.jpg" alt="" width='120'>
                </div>
                <div class="althem-left-search">
                    <input type="text" name="search" placeholder="Search" />
                </div>
                <div class="althem-left-social">
                    <a href=""><img  src="<?= BASE_URL ?>/style/img/fa-brands_twitter-square.png" alt="" width='30' /></a>
                    <a href=""><img  src="<?= BASE_URL ?>/style/img/logos_youtube-icon.png" alt="" width='30' /></a>
                    <a href=""> <img  src="<?= BASE_URL ?>/style/img/logos_telegram.png" alt="" width='30' /></a>
                    <a href=""><img  src="<?= BASE_URL ?>/style/img/fontisto_instagram.png" alt="" width='30' /></a>
                </div>
            </div>
            <div class="col9 althem-right">
                <div  class="althem-right-sub">
                    <div  class="althem-right-sub-title"><a href="">Company</a></div>
                    <div  class="althem-right-sub-content">
                        <ul>
                            <li><a href="">Home</a></li>
                            <li><a href="">AI Trade</a></li>
                            <li><a href="">Social</a></li>
                            <li><a href="">Knowledge</a></li>
                            <li><a href="">News</a></li>
                        </ul>
                    </div>
                </div>
                <div  class="althem-right-sub">
                    <div  class="althem-right-sub-title"><a href="">Earn</a></div>
                    <div  class="althem-right-sub-content">
                        <ul>
                            <li><a href="">AI Trade</a></li>
                            <li><a href="">Stake</a></li>
                            <li><a href="">Make & Sell Skill Book</a></li>
                            <li><a href="">Alchemist Launchpad</a></li>
                        </ul>
                    </div>
                </div>
                <div  class="althem-right-sub">
                    <div  class="althem-right-sub-title"><a href="">Resources</a></div>
                    <div  class="althem-right-sub-content">
                        <ul>
                            <li><a href="">Whitepaper</a></li>
                            <li><a href="">Roadmap</a></li>
                        </ul>
                    </div>
                </div>
                <div  class="althem-right-sub">
                    <div  class="althem-right-sub-title"><a href="">Contacts</a></div>
                    <div  class="althem-right-sub-content">
                        <ul>
                            <li><a href="">Email</a></li>
                            <li><a href="">Mobile</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">Copyright @ 2021, TheAlchemist.ai</div>
</footer>
<!--<script language="javascript">
    document.onmousedown = disableclick;
    function disableclick(event) {
        if (event.button == 2)
            return false;
    }
</script>
<script lang="javascript">(function() {var pname = document.title;var ga = document.createElement('script'); ga.type = 'text/javascript';ga.src = '//live.vnpgroup.net/js/web_client_box.php?hash=0c4c229aa44aa81e5e5c63af4b148ac3&data=eyJzc29faWQiOjMzNTU2ODAsImhhc2giOiIzYTk0ZmViNjg1MTc1MjVjNGYwYzAyNTA1YTY0ZjhjMyJ9&pname='+pname;var s = document.getElementsByTagName('script');s[0].parentNode.insertBefore(ga, s[0]);})();</script><noscript><a href="http://www.vatgia.com" title="vatgia.com" target="_blank">Tài trợ bởi vatgia.com</a></noscript><noscript><a href="http://vchat.vn" title="vchat.vn" target="_blank">Phát triển bởi vchat.vn</a></noscript><noscript><a href="http://123doc.org" title="123doc.org" target="_blank">Partner vchat.vn</a></noscript>		-->