<!DOCTYPE HTML>
<?php
$action = $this->action;
$tab = $this->tab;
?>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TheAlchemist</title>
        <link rel="shortcut icon" href="<?= BASE_URL ?>/favicon.ico" />
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/bootstrap.css">
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/social.css">
        <script src="<?= BASE_URL ?>/style/js/jquery-3.6.0.min.js"></script>
        <script src="<?= BASE_URL ?>/style/js/bootstrap.min.js"></script>
        <script src="<?= BASE_URL ?>/style/js/social.js"></script>
        <script src="https://malsup.github.io/jquery.form.js"></script>
        <script src="<?= BASE_URL ?>/style/js/bootstrap-select.js"></script>
        <script src="<?= BASE_URL ?>/style/js/highchart/highcharts.js"></script>
        <script src="<?= BASE_URL ?>/style/js/highchart/series-label.js"></script>
        <script src="<?= BASE_URL ?>/style/js/highchart/exporting.js"></script>
        <script src="<?= BASE_URL ?>/style/js/highchart/export-data.js"></script>
        <script src="<?= BASE_URL ?>/style/js/highchart/accessibility.js"></script>
        <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/bootstrap-select.css">
        <script src="<?= BASE_URL ?>/style/js/bootstrap-select.js"></script>
        <script>
            $("html, body").animate({scrollTop: 750}, 1000);
        </script>


    </head>
    <body>
        <div id="container">

            <?=
            $this->action("header", "index", "Social", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
            <?=
            $this->action("content", "index", "Profile", array(
                'language' => $this->language,
                'id_active' => $this->id_active,
                'moduleTitle' => $this->module))
            ?>
            <a class="work-home" title="Back home" href="<?= BASE_URL ?>/vn/trade"></a>
        </div>

    </body>

</html>
