<?php
$symboyAlls = $this->symboyAlls;

$date = $_REQUEST['date'] ? $_REQUEST['date'] : date('Y-m-d');
$dateTo = $_REQUEST['date_to'] ? $_REQUEST['date_to'] : date('Y-m-d');
$cur = $_REQUEST['cur'] ? $_REQUEST['cur'] : ($symboyAlls[0]['symbol'] ?? 'AAVEUSDT');

$strDate = strtotime($date) . '000';
$strDateTo = strtotime($dateTo) . '000';

$curDatas = [];
$curNext = "";
if ($symboyAlls) {
    $flag = 0;
    foreach ($symboyAlls as $row) {
        $curDatas[] = $row['symbol'];
    }

    foreach ($curDatas as $a) {
        if ($flag) {
            $curNext = $a;
            break;
        }


        if ($a == $cur) {
            $flag = 1;
        }
    }
}

if (!$flag || !$curNext)
    die("OK");
?>

<html>
    <script src="<?= BASE_URL ?>/style/js/jquery-3.6.0.min.js"></script>
    <script>
        var burl = "https://api.binance.com";

        var query = '/api/v3/klines';


        query += '?symbol=<?php echo($cur) ?>&interval=1d&startTime=<?php echo($strDate) ?>&endTime=<?php echo($strDateTo) ?>';

        var url = burl + query;

        console.log(url);

        var ourRequest = new XMLHttpRequest();
        var datas = [];
        ourRequest.open('GET', url, true);
        ourRequest.onload = function () {
            console.log(JSON.parse(ourRequest.responseText));
            var data = ourRequest.responseText;
            $.ajax({
                type: "POST",
                //url: "http://localhost/demo/vn/processd1",
                url: "https://thealchemist.ai/vn/processd1",
                cache: false,
                data: {
                    'data': JSON.parse(data),
                    'symbol': '<?php echo($cur) ?>'
                },
                dataType: "json",
                success: function (response) {

                    if (!response.error) {
                        $("#msg").addClass('alert-success').html(response.msg);
                    } else {
                        $("#msg").addClass('alert-danger').html(response.msg);
                    }
                }
            });
        };
        ourRequest.send();

        var urlNext = 'https://thealchemist.ai/vn/send?date=' + '<?php echo($date) ?>' + '&date_to=<?php echo($dateTo) ?>' + '&cur=' + '<?php echo($curNext) ?>';
        setTimeout(function () {
            window.location.href = urlNext;
        }, 100);


    </script>
    <body>
        <div id="msg"></div>
    </body>

</html>