<?php
$plugins = $this->Plugins;
$studies = $plugins->get('study', 'RSI7');
$tab = $plugins->get('tab', 'USDT');
$type = $plugins->get('type', '1D');
$list = $plugins->get('list', 'st');
$symbol = $this->symbol; // Fake
$rightPosts = $this->rightPosts;
$postCurrent = $this->postCurrent;
$postHighLight = $this->highlightpost;
?>
<!DOCTYPE html>
<html>
    <?php include __DIR__ . '/layouts/head.phtml'; ?>
    <link rel="stylesheet" href="<?= BASE_URL ?>/style/css/new-css/al-trade.css">
<body>

<!--header-->
<?php include __DIR__ . '/layouts/header.phtml'; ?>
<!--end header-->

<!--Al-trade_body-->
<div class="wapper">
        <!--Notice Box--> 
        <div class="container"> 
            <div class="altrade-body">
                    <div class="notice-box">
                        <a> Alchemist primary alert!<span style="color: #1A64F0;" href="#"> SEE MORE</span></a>
                    </div>    
                    <div class="confluence-bar">
                        <div class="confluence-box-2 <?= $studies == 'RSI7' ? "confluence-box-2-active" : "" ?>" >
                            <a href="?study=RSI7">RSI-7 &amp; Candlestick Model</a>
                        </div>
                        <div class="confluence-box-2 <?= $studies == 'RSI14' ? "confluence-box-2-active" : "" ?>" >
                            <a href="?study=RSI14">RSI-14 &amp; Candlestick Model</a>
                        </div>
                            
                        <div class="stablecoin-frame">
                            
                            <a type="button" class="stablecoin-button-1 
                                    <?= $tab == 'USDT' ? "stablecoin-button-1-active" : "" ?>" href="?tab=USDT&study=<?= $studies ?>">
                                
                                    <span class="label-satblecoin">
                                        <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/icon-usdt.svg">
                                    </span>
                                        <span style="font-size: 16;">Tether </span>
                                        <span style="color: #1A64F0;">USDT</span>
                                
                            </a>
                            
                            <a href="?tab=BTC&study=<?= $studies ?>" class="stablecoin-button-1 
                                                    <?= $tab == 'BTC' ? "stablecoin-button-1-active" : "" ?>">
                                
                                    <span class="label-satblecoin">
                                            <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/icon-btc.svg"> 
                                    </span>  
                                        <span>Bitcoin</span>
                                        <span style="color: #1A64F0;">BTC</span>
                                
                            </a>
                            <a href="?tab=BUSD&study=<?= $studies ?>" type="button" class="stablecoin-button-1 
                                                <?= $tab == 'BUSD' ? "stablecoin-button-1-active" : "" ?>">
                                
                                    <span class="label-satblecoin">
                                        <img src="<?= BASE_URL ?>/style/css/new-images/icon-coin/icon-busd.svg" alt="icon-busd.svg">
                                    </span>
                                        <span>Binance</span>
                                        <span style="color: #1A64F0;">USD</span>
                             <!--time-frame -->    
                            </a>
                                <img src="<?= BASE_URL ?>/style/css/new-images/Vector 62 (Stroke).svg" alt="Vector 62 (Stroke).svg">
                            <a href="?type=1D&study=<?= $studies ?>&tab=<?= $tab ?>" type="button" class="timeframe-button
                                <?= $type == '1D' ? "timeframe-button-active" : "" ?>">
                                <span>1D</span>        
                            </a>
                            <a href="?type=4H&study=<?= $studies ?>&tab=<?= $tab ?>" class="timeframe-button
                                <?= $type == '4H' ? "timeframe-button-active" : "" ?>">
                                <span>4H </span>
                            </a>
                            <a href="?type=1H&study=<?= $studies ?>&tab=<?= $tab ?>" class="timeframe-button 
                                <?= $type == '1H' ? "timeframe-button-active" : "" ?>">
                                <span>1H</span>
                            </a>
                            <a href="?type=30m&study=<?= $studies ?>&tab=<?= $tab ?>" class="timeframe-button
                                <?= $type == '30m' ? "timeframe-button-active" : "" ?>">
                                <span>30m</span>
                            </a>
                        </div>
             
                        <!--tutorial-->
                        <div class="tutorial-frame" type="button">
                            <label><img src="<?= BASE_URL ?>/style/css/new-images/video-circle.svg" alt="video-circle.svg""> Tutorial</label>                          
                        </div>
                        <div class="tutorial-frame-1" type="button">
                            <label><img src="<?= BASE_URL ?>/style/css/new-images/book.svg" alt="book.svg"> Guide</label>                            
                        </div>
            
                        <!--coin-name-->
        
                        <div class="coin-name">
                            <a><?= $symbol ?></a>
                        </div>
            
                        <div class="coin-suggestion">
                            <div class="text-effect text-effect-active">
                                <a href="http://thealchemist.ai/en/trade2">
                                Suggestion
                                </a>
                            </div>
                            <div class="text-effect">
                                <a href="http://thealchemist.ai/en/trade2">
                                My Watchlist
                                </a>
                            </div>
                        </div>
            
                        <div class="history-box">
                                <br>
                                <a style="font-family: 'Poppins'; font-size: 18px; ">Highlight</a>
                                <br>
                                
                                <table class="history-table" <?= $activeUSD ?>" id="usd">
                                    <thead>
                                        <tr class="tr-bottom text_headerlist">
                                            <th scope="col" style="color:#1A64F0;">Name</th>
                                            <th scope="col" style="color:#1A64F0;">Discovered on</th>
                                        </tr>
                                    </thead>
                                    <tbody class="tr-bottom text_onlist">
                                <?php if ($postHighLight): ?>
                                    <?php foreach ($postHighLight as $hight): ?>
                                        <tr style="border-bottom: 1px solid #F6F6F6;">
                                            <td class="align-middle">
                                                <a href="?ID=<?= $hight['id'] ?>&list=<?= $list ?>&symbol=<?= $post['symbol'] ?>&tab=<?= $tab ?>&type=<?= $type ?>&study=<?= $studies ?>"
                                                   style="color:<?= $hight['model_type'] == "UP" ? '#00BD46' : '#CC0001' ?>;" 
                                                   class="trade-coin-a" 
                                                   data-placement="right" 
                                                   title="<?= $hight['symbol'] ?>">
                                                    <?= get_quote(strip_tags($hight['symbol']), 6) ?>
                                                </a>
                                            </td>
                                            <td class="align-middle">
                                                <span class="pr-2" data-placement="right">
                                                    <span class='desc'><?= date('H:i - d/m' , strtotime($hight['date_find'])) ?></span>
                                                </span>
                                            </td>
                                        </tr>
                                        
                                   
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td class="align-middle" colspan="3">
                                            Nothing
                                        </td>
                                    </tr>

                                <?php endif; ?>
                            </tbody>
                                </table>
                        </div>
                    
                
        
                        <!--TDV JS--> 
                        <div class="tradingview-frame">
                            <div class="tradingview-widget-container mb-3">
                                <div id="crypt-candle-chart"></div>
                            </div>
                        </div>
               
                            <!--listcoinbox-->
                            
                                <div class="listcoin-box">
                                    <div class="standard-box">
                                        <div class="text-effect <?= $list == 'st' ? "text-effect-active" : "" ?>" >
                                            <a href="?list=st&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=<?= $type ?>&study=<?= $studies ?>">
                                                Standard
                                            </a>
                                        </div>
                                        <div class="text-effect <?= $list == 'my' ? "text-effect-active" : "" ?>" >
                                            <a href="?list=my&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=<?= $type ?>&study=<?= $studies ?>">
                                                My List
                                            </a>
                                        </div>
                                        <div class="text-effect <?= $list == 'pro' ? "text-effect-active" : "" ?>" >
                                            <a href="?list=pro&symbol=<?= $symbol ?>&tab=<?= $tab ?>&type=<?= $type ?>&study=<?= $studies ?>">
                                                 Pro List
                                            </a>
                                        </div>
                                    </div>
                                    <div class="tab-pane trade-container-right-tab work-form-item-tab-info-content <?= $activeList ?>">
                                        <table class="listcoin-table">
                                            <thead>
                                                <tr class="tr-bottom text_headerlist">
                                                    <th scope="col" style="color:#1A64F0;">Name</th>
                                                    <th scope="col" style="color:#1A64F0; width:200px; height: 30px;" colspan="2">Discovered on</th>
                                                </tr>
                                            </thead>

                                            <tbody class="tr-bottom text_onlist" >
                                                    <?php foreach ($rightPosts as $post): ?>
                                                    <tr style="border-bottom: 1px solid #F6F6F6; height:38px;" class="<?= $postCurrent['ID'] == $post['ID'] ? "trade-coin-tr-active" : "" ?>">
                                                        <td class="align-middle">
                                                            <a href="?ID=<?= $post['id'] ?>&list=<?= $list ?>&symbol=<?= $post['symbol'] ?>&tab=<?= $tab ?>&type=<?= $type ?>&study=<?= $studies ?>"
                                                               style="color:<?= $post['model_type'] == "UP" ? '#00BD46' : '#CC0001' ?>;" 
                                                               class="trade-coin-a" 
                                                               data-placement="right" 
                                                               title="<?= $post['symbol'] ?>">
                                                                <?= get_quote(strip_tags($post['symbol']), 6) ?>
                                                            </a>
                                                        </td>
                                                        <td class="align-middle">
                                                            <span class="pr-2" data-placement="right">
                                                                <span class='desc'><?= date('H:i - d/m' , strtotime($post['date_find'])) ?></span>
                                                            </span>
                                                        </td>
                                                    </tr>
                                                    <?php endforeach; ?>
                                            </tbody> 
                                        </table>
                                    </div>
                                </div>
             
                    <!--order infomation-->   
              
                            <div class="order-information"> 
                                <br>
                                   <a style="font-family: 'Poppins'; font-size: 18px; "> <strong>Order Information</strong></a>
                                        <!--coin-name-->
                                <div class="information-box">
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Trading &nbsp; Pair:</a>
                                            <a class="title-box-2"> 
                                                <?= $symbol ?> 
                                            </a>
                                        </div>
                                    </div>
                                    <!--Patterm-->
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Detected&emsp;Pattern:</a>
                                            <a class="title-box-long"> 
                                                <?= $postCurrent['model_title'] ?? '' ?> 
                                            </a>
                                        </div>
                                    </div>
                                        <!--Entry-->
                                    <div class="coin-box-1">
                                            <div class="text-box-frame left-frame">       
                                                <a class="title-box-1">Entry &emsp; Point:</a>
                                                <a class="title-box-2">--</a>
                                            </div>
                                    </div>
                                        <!--Target-->
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #00BD46;" class="title-box-1">Target &emsp; Point:</a>
                                            <a style="color: #00BD46" class="title-box-2">--</a>
                                        </div>
                                    </div>
                                        <!---Stop-loss-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #CC0001;" class="title-box-1">Stop Loss:</a>
                                            <a style="color: #CC0001;" class="title-box-2">--</a>
                                        </div>
                                    </div>
                                        <!---Reward-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #00BD46;" class="title-box-1">Reward:</a>
                                            <a style="color: #00BD46;" class="title-box-2">--</a>
                                        </div>
                                    </div>
                                        <!---Risk-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a style="color: #CC0001;" class="title-box-1">Risk:</a>
                                            <a style="color: #CC0001;" class="title-box-2">--</a>
                                        </div>
                                    </div>
                                        <!---Detected-->
                                    <div class="coin-box-1">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Detected &emsp; on:</a>
                                            <a class="title-box-2"><?= date('H:i - d/m' , strtotime($postCurrent['date_find'])) ?></a>
                                        </div>
                                    </div>
                                            <!---Status-->
                                    <div class="coin-box-2">
                                        <div class="text-box-frame left-frame">
                                            <a class="title-box-1">Status:</a>
                                            <a class="title-box-2">
                                            --
                                            </a>
                                        </div>
                                    </div>
                        
                                    <!--End Trading Pair Information-->
                                    <!--Trading-Strategy-->
                            
                                    <div class="trading-strategy-box">
                                        <div class="trading-text-box">Trading Strategy</div>
                                            <div class="detected-box">
                                                <div class="text-box-frame left-frame"> 
                                                    <a style="width:fit-content; font-size: 12px;"class="title-box-1">Detected Pattern:</a>
                                                    <a style="color:#1A64F0; font-size: 12px;" class="title-box-2">
                                                        <?= $postCurrent['model_title'] ?? '' ?>
                                                    </a>
                                                </div>
                                            

                                                <!--left-box-->
                                                <div class="left-detected-box">
                                                    <div class="sub-detected-box">
                                                        <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">Entry Point:</a>
                                                        <a style="width:fit-content; font-size: 16px;">--</a>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">DCA1</a>
                                                    <a style="width:fit-content; font-size: 16px;">--</a>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">DCA2</a>
                                                    <a style="width:fit-content; font-size: 16px;">--</a>
                                                </div>
                                            </div>
                                            
                                            <div class="right-indicator left-frame">
                                                <a style="width:fit-content; font-size: 12px;"class="title-box-1">Indicator:</a>
                                                <a style="color:#1A64F0; font-size: 12px;" class="title-box-2"><?= $studies . ' ~ ' . $postCurrent[strtolower($studies)] ?></a>
                                            </div>

                                            <div class="right-detected-box">
                                                <div class="sub-detected-box">
                                                    <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">Target Point:</a>
                                                    <a style="width:fit-content; font-size: 16px;">--</a>
                                                </div>
                                                <div class="risk-reward-box">
                                                    <div class="small-sub-detected-box">
                                                        <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">Risk:</a>
                                                        <a style="width:fit-content; font-size: 16px;">--</a>
                                                    </div>
                                                    <div class="small-sub-detected-box-1">
                                                        <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">Reward:</a>
                                                        <a style="width:fit-content; font-size: 16px;">--</a>
                                                    </div>
                                                </div>
                                                <div class="sub-detected-box">
                                                    <a style="width:fit-content; font-size: 14px; color:#7D7D7D;">Stop Loss</a>
                                                    <a style="width:fit-content; font-size: 16px;">--</a>
                                                </div>
                                
                                            </div>
                                        </div>
                                            
                                            <!--button-Save-order-->
                                            <div class="save-button-frame">
                                                <?php if ($this->save): ?>
                                                <button class="save-order-button trade-container-bottom-item2-save" disabled"><a><b>Processing</b></a>

                                                <?php else: ?>
                                                    <button class="save-order-button trade-container-bottom-item2-save" rel-id="<?= $postCurrent['subID'] ?>" rel-type="<?= $postCurrent['type'] ?>"><a><b>Save</b><a></button>
                                                <?php endif; ?>
                                            </div>
                                            <!-- 
                                                <a style="color:#FFFFFF; font-size: 16px;"><b>Save</b></a> 
                                            -->
                                                   
                                           
                                           
                                            <div class="save-text-notice">
                                                <?php if ($this->save): ?>
                                                    Your investment is being analyzed in &nbsp;<a href="profile">My Dashboard</a>
                                                <?php else: ?>
                                                    Please keep in mind that these are only suggestions,
                                                    <br>consider them carefully before trading!
                                                <?php endif; ?>
                                                </a>
                                            </div>
                                            </div>
                        
                                            <!--bottom-right-box-->
                                                
                                                        <div class="top-bottom-right" <?= $activeUSD ?>" id="usd">
                                                                <a style="position: absolute;
                                                                width: 180px;
                                                                left: calc(50% - 180px/2);
                                                                top: 24px; font-size: 18px; font-family: 'Poppins'; font-weight: 700;">How to trade with Candlestick</a>
                                                                <div class="text-model-information">
                                                           
                                                                    <div class="infomartion-frame model-name">
                                                                            <a class="model-text-box" style="text-align: left;">Model:</a>
                                                                            <a  href='#' class="model-name">
                                                                                <?= $postCurrent['model_title'] ?? $formular['title'] ?>
                                                                            </a>
                                                                    </div>
                                                                </div>
                                                                <div class="learn-now-box">
                                                                    <a href="http://thealchemist.ai/en/academy" >No idea what
                                                                        <?= $postCurrent['model_title'] ?? $formular['title'] ?> is?
                                                                    
                                                                    <br>
                                                                    <b>Learn now!
                                                                    </b>  
                                                                    </a>
                                                                </div>
                                                                
                                                                <div class="myformula-text-box">
                                                                    <a href="http://thealchemist.ai/en/work" style="color: #7D7D7D;">Got a strategy? Turn it into an algorithm with <a href="work" style="color:#1A64F0;">
                                                                    <b>My Formula</b></a>
                                                                </div>
                                                            
                                                        </div>
                                                    
                                                
                                
                                                
                                    
                                            <div class="bottom-right-box-end">
                                                    <a class="text-box-manage">Manage your Portfolio</a>
                                                    <div class="image-box-manage">
                                                        <img src="<?= BASE_URL ?>/style/css/new-images/manage-img.svg" alt="portorio">
                                                    </div> 
                                                    <button class="button-go-dashboard">
                                                        <a href="profile" style="color: white;">Go to <b>My Dashboard</b></a>
                                                    </button>
                                            </div>
                            </div>
                                
                        </div>
                                <!--end-right-box-->
                    </div>           
            </div>
        </div>
</div>



<!--footer-->
<?php include __DIR__ . '/layouts/footer.phtml'; ?>
<!--End footer-->  

<!--popup connect wallet-->
<?php include __DIR__ . '/layouts/pop.phtml'; ?>
<!--End popup connect wallet--> 
<?php include __DIR__ . '/layouts/scrips.phtml'; ?>

        <script src="<?= BASE_URL ?>/style/js/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/tv.js"></script>
        <script src="<?= BASE_URL ?>/style/js/new/mainh4.js"></script>
        <script  type="text/javascript">
            var studies = <?php echo json_encode($study); ?>;
            if (document.getElementById('crypt-candle-chart')) {
                new TradingView.widget(
                        {
                            "autosize": true,
                            "symbol": "<?= $symbol ?>",
                            "interval": "<?php echo($interval); ?>",
                            "timezone": "Europe/Greenwich",
                            "theme": "Light",
                            "style": "1",
                            "locale": "en_EN",
                            "toolbar_bg": "rgba(255, 255, 255, 1)",
                            "enable_publishing": false,
                            "allow_symbol_change": true,
                            "show_popup_button": true,
                            "popup_width": "1000",
                            "popup_height": "1000",
                            "withdateranges": true,
                            "container_id": "crypt-candle-chart",
                            "studies_overrides": {
                                "rsi.rsi.plot.color": "#2196f3",
                                "rsi.level.0": 20,
                                "rsi.level.1": 80
                            },
                            "studies": studies
                        }
                );
            }
        </script>
    </body>
    </html>